name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      CLANG_PATH: clang
      OBJDUMP_PATH: llvm-objdump
      OBJCOPY_PATH: llvm-objcopy
      NM_PATH: llvm-nm

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y build-essential
        sudo apt-get install -y clang
        sudo apt-get install -y llvm

    - name: Build
      run: |
        export CC=clang 
        make test